version: '3.8'

services:
  app:
    build: .
    container_name: peligro-laravel-app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html  # ✅ COMPARTIR TODO el proyecto
    environment:
      # ... tus variables
    networks:
      - custom_network

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html  # ✅ MISMO volumen que la app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - custom_network

networks:
  custom_network:
    driver: bridge